Traceback (most recent call last):

  File "./pylib/Tkinter.py", line 1363, in __call__

  File "./ganymed_2/uibase/action.py", line 2079, in event

  File "./ganymed_2/uibase/action.py", line 2035, in do_key

  File "./ganymed_2/uibase/action.py", line 217, in execute

  File "./ganymed_2/uibase/action.py", line 300, in _execute

StandardError: Invalid Command

